Update Mat.drawContours-typing
justadudewhohacks/opencv4nodejs pull request #739
Opened 2020-07-06 13:49 UTC by FluidSense

Resolves https://github.com/justadudewhohacks/opencv4nodejs/issues/691.

I would prefer for the actual method to accept contours instead of updating the type to correctly state `Point2[]` as the input, but wrong typings are quite misleading and easy to fix.

Please tell me if the proposed type still is wrong, it is based on the linked issue as well as personal usage, but I might have missed something and could gladly update it.

2020-12-07 14:49 UTC, ViniDalvino commented
I really want the patch to be applied as without the patch it's almost impossible to use the library with typescript.

2020-12-07 15:24 UTC, ViniDalvino approved these changes

2020-12-09 18:48 UTC, ViniDalvino commented
These type def are still wrong. Here are my fix for draw contours: `  drawContours(contours: Point2[][], countourIdx: number, color: Vec3, thickness?: number, lineType?: number, _lineType?: number, _thickness?: number, shift?: number): void;
`

2020-12-10 07:20 UTC, FluidSense commented
@ViniDalvino I haven't used this since I opened the PR, but aren't usually underscored variables meant to signify private variables?
Also, do you need an array of arrays of Point2, which is also an array (of two items)?
If you are certain about it, feel free to create a new PR, reference to this one and I'll close it in favor for yours. 
However, there haven't been a lot of activity in this repo since 4th of june, so there ain't much chance that any of the PR's will be merged.

2020-12-10 10:04 UTC, ViniDalvino commented
The underscore is used cuz I was trying to gues what the parameter were

2021-01-19 13:10 UTC, tomkha commented
Have a look at the real arguments order in DrawContoursWorker
https://github.com/justadudewhohacks/opencv4nodejs/blob/master/cc/imgproc/MatImgprocBindings.h#L2054

also here https://docs.opencv.org/4.5.1/d6/d6e/group__imgproc__draw.html#ga746c0625f1781f1ffc9056259103edbc

I submitted one more version of the PR: https://github.com/justadudewhohacks/opencv4nodejs/pull/794

2021-01-19 13:26 UTC, tomkha requested changes
The first three required parameters are correct but the following ones are not. They doesn't match the real definition in OpenCV lib (https://github.com/justadudewhohacks/opencv4nodejs/issues/691)

As far as I understand it should be 
```
drawContours(contours: Point2[][], contourIdx: number, color: Vec3, thickness?: number, lineType?: number, hierarchy?: Vec4[], maxLevel?: number, offset?: Point2): void;
```

2022-04-13 06:29 UTC, UrielCh commented
[PR794](https://github.com/justadudewhohacks/opencv4nodejs/pull/794)

is merged can be close

2022-04-15 14:18 UTC, closed without merging